baseURL = "https://stankoua.github.io/"
languageCode = "en-us"
title = "stefshine's playground"
theme = "terminal"
paginate = 5
enableEmoji = true

[params]
  themeColor = "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # show selector to switch language
  showLanguageSelector = true
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    languageName = "English"
    title = "stefshine's playground"
    subtitle = "Gathered thoughts of a wannabe functional programmer"
    keywords = "programming,functional programming,scala,haskell"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Stefshine's playground"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/en/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Conferences"
        url = "/en/conference-work"
  [languages.fr]
    languageName = "Français"
    title = "Terrain de jeu de stefshine"
    subtitle = "Recueil de pensées d'un aspirant développeur fonctionnel"
    keywords = "programmation,programmation fonctionnelle,scala,haskell"
    copyright = ""
    menuMore = "Afficher plus"
    readMore = "Voir plus"
    readOtherPosts = "Lire les autres posts"

    [languages.fr.params.logo]
      logoText = "Stefshine's playground"
      logoHomeLink = "/fr"

    [languages.fr.menu]
      [[languages.fr.menu.main]]
        identifier = "about"
        name = "A propos de moi"
        url = "/fr/fr/about"
      [[languages.fr.menu.main]]
        identifier = "showcase"
        name = "Conférences"
        url = "/fr/fr/conference-work"
      [[languages.fr.menu.main]]
        identifier = "courses"
        name = "Cours"
        url = "/fr/fr/cours"
